language: node_js

node_js:
  - 20

install:   
  - npm ci

  cache: 
    directories:    
      - ~/.npm    
      - ./node_modules    
      - ~/.cache  override:    
      - npm ci    
      - npm run cy:verify

  script:    
    - ng lint    
    - ng build --prod    
    - npm run cy:verify    
    - npm run ci:cy-run